version: "3.9"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    image: littlebirdie-django:latest
    container_name: celery_worker
    command: celery -A LittleBirdie worker --pool=solo --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
